### ISSUE TITLE
Open WSL on Ubuntu (not Windows)

### ISSUE THREAD

**Issue by andrerferrer** [lewagon/setup#156]
So, I just finished the setup for #409 and several students got confused due to the fact that WSL is going to open on you Windows User folder instead on Ubuntu's home folder.
So, we need to click on the `down arrow > settings` OR `ctrl+,` and then add "starting directory" inside of the "profiles" key:

```
        "defaults":
        {
            // Put settings here that you want to apply to all profiles
            "startingDirectory" : "//wsl$/Ubuntu/home/andrerferrer"
        },
```

Of course `andrerferrer` should be replaces with the student's username.

I'm not sure on how to implement this on Windows.md. Hence this issue submited.

Ty

**Comment by Disco-Chef** [comment]
![image](https://user-images.githubusercontent.com/49205098/80760175-c6535180-8b38-11ea-9573-56e0d1ba02ec.png)
I was going to open the same issue sort of, with the added comment that perhaps it would be interesting in telling the students to set the default terminal profile to be Ubuntu in the Windows Terminal (Preview) Settings below:
![image](https://user-images.githubusercontent.com/49205098/80760303-f7cc1d00-8b38-11ea-9819-185c5bd822f7.png)

and set the defaultProfile to match the guid of the Ubuntu profile (instead of the default Windows Powershell)
![image](https://user-images.githubusercontent.com/49205098/80760569-63ae8580-8b39-11ea-9c1e-5070758e9014.png)
