### ISSUE TITLE
/bin/yarn:5: warning: Insecure world writable dir /mnt/c in PATH, mode 040777 - WSL2

### ISSUE THREAD

**Issue by jramiresbrito** [lewagon/setup#174]
This warning is being shown when I ran yarn. It also appear when I start the server with `rails s`.

```
/home/joao/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.1/lib/rails/app_loader.rb:53: warning: Insecure world writable dir /mnt/c in PATH, mode 040777
```

Maybe chmod solve the problem?

PS: I'm on WSL2

**Comment by barangerbenjamin** [comment]
Hi @jramiresbrito 
Thanks for reporting.

This warning is present because the Linux PATH env variable contains some windows paths such as `/mnt/c`. Even if Windows and Linux are co-habiting well so far, they still don't understand each other filesystem's permissions. The only way known to remove those errors would be to remove those paths from the PATH env variable. But that would break the use of VSCode from the WSL2 terminal.

I'll have a look on to silence those warnings but for the time being, please ignore those 🙌

**Comment by jramiresbrito** [comment]
Ok, thank you.

**Comment by barangerbenjamin** [comment]
Hi @jramiresbrito 
You can check the cheatsheet for WSL to find how to silence those warnings :) 
https://github.com/lewagon/setup/blob/master/wsl_cheatsheet.md#insecure-world-writable

**Comment by jramiresbrito** [comment]
When I try to save the options in wsl.conf:

```
[automount]
options="metadata,umask=0033"
```
This permission error prompts:
```
Failed to save 'wsl.conf': Unable to write file 'vscode-remote://wsl+ubuntu/etc/wsl.conf' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/etc/wsl.conf')
```

I tried with sudo, using VsCode, using Vim, using echo any aways no permission...

The file was succesfully created but I cant add the options

**Comment by barangerbenjamin** [comment]
@jramiresbrito

Yes, my bad. It works with a `sudo vi ...`
I've changed the instructions to a full command line approach if you go back to the cheatsheet 🙏

**Comment by jramiresbrito** [comment]
It worked! I'll report if I still seeing any warning. Thank you @barangerbenjamin

**Comment by jramiresbrito** [comment]
Hey @barangerbenjamin unfortunatelly i still having warning. I ran yarn in a project and it shows:

`./bin/yarn:5: warning: Insecure world writable dir /mnt/c in PATH, mode 040777`

I successfully added automount
![wsl2-warning](https://user-images.githubusercontent.com/47673606/85099877-fe8c1d80-b1d4-11ea-8cdc-fe33733033fb.png)
