### ISSUE TITLE
Homebrew install on M1 macs

### ISSUE THREAD

**Issue by stephlaf** [lewagon/setup#289]
We had some problems on the setup for the new M1 Macs, and found this solution. 
I figure it would be a good thing to update the setup instructions so they don't try installing in the actual specified way.

To install Homebrew and Ruby on the new M1 Mac, if they have already installed Homebrew with the supplied command, and are not able to install `ruby`

1. We had to uninstall Homebrew first:
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"`

2. Then install the M1 version of Homebrew:
`arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`

3. Then prefix `brew install` with the specific architecture:
`arch -x86_64 brew install rbenv`

4. And we were then be able to install `ruby`

**Comment by dmilon** [comment]
Hi @stephlaf :wave: 

It looks like our web setup is compatible with M1 out of the box without using Rosetta anymore: 

![image](https://user-images.githubusercontent.com/37899667/135824175-15c32e5c-6bf3-4da7-b9a0-9ee870919cac.png)

I still need to check that **everything** is working fine since it appears some packages still depend on Rosetta (like the Heroku CLI for example) but may fallback automatically to Rosetta without any specific configuration (but maybe only on BigSur :smile: )

I'll use this issue to document my finding about this topic.

**Comment by stephlaf** [comment]
Thanks Damien. 


Stéphane Lafontaine
Sonorisateur FOH, Retours
+1 (514) 544-1597
