### ISSUE TITLE
nvm cache takes up 10gb

### ISSUE THREAD

**Issue by magerags** [lewagon/setup#343]
On a fresh install nvm creates a cache that is around 9 to 12gb.

As many students use Macbooks with limited space, maybe it should be recommended to install node via homebrew rather than nvm or at least run `nvm cache clear` after install

**Comment by dmilon** [comment]
Hi @magerags :wave: Thank you for your report :pray: 

As mentioned [here](https://github.com/nvm-sh/nvm/issues/2478#issuecomment-812942578) nvm shouldn't be installed via homebrew. But I agree that we should unload the disk space of your student MacBooks with limited space. Since we are installing node only once, we don't need the cache so I've added `nvm cache clear` in the setup instructions :ok_hand: 

https://github.com/lewagon/setup/pull/344
