### ISSUE TITLE
Set default nodeJS 18.18.0

### ISSUE THREAD

**Issue by carlosferrerdev** [lewagon/setup#441]
On September 11, 2023, NodeJS 16 was discontinued and will no longer receive support or security updates. 

Update the kitt material to install the latest stable LTS version of NodeJS, which is version 18.18.0

**Comment by ajdubovoy** [comment]
@Eschults I don't think updating node would be a bad idea at all. In terms of technically doing it in the setup guide, it'd be quite easy. But how do you feel about us doing such an update?

**Comment by Eschults** [comment]
Hello @ajdubovoy 👋 

We definitely should, the [recommended LTS version](https://nodejs.org/en) is now `20`, let's take the opportunity bump to ruby `3.2.3` at the same time (last version bump was handled in https://github.com/lewagon/setup/pull/391). Let's prepare the PRs to plan a release before Q2 batches start 👌  

Besides [challenges](https://github.com/search?q=repo%3Alewagon%2Ffullstack-challenges+3.1.2&type=code), this change impacts a lot of boilerplates / livecodes repositories, both [in the @lewagon org](https://github.com/orgs/lewagon/teams/web-dev-editors/repositories) and in the [@lewagon-assess org](https://github.com/orgs/lewagon-assess/repositories?q=&type=template&language=&sort=) for the French certification exam.

Let's start by creating PR using the same branch name convention for all repos, and we can decide later how we plan to release the change 🚀

**Comment by ajdubovoy** [comment]
Also I don't think I have access to @lewagon-assess

**Comment by Eschults** [comment]
> Sounds good! But also sounds like quite a huge project unless I'm misunderstanding. I'm happy to take it on, but is there any sense in us coming up with a strategy beforehand? Or is it better if I just dive into all the repos and see if anything breaks when I upgrade....?

Let's start by identifying the repos that need a change in the `.rubyversion` / `Gemfile` and prepare the PRs, this is a repetitive task that could easily be delegated, there shouldn't be any breaking changes due to the ruby bump so I don't think we need to thoroughly test every repo, maybe we can spend some time on the ones w/ more JavaScript dependencies but it could be quite straightforward if we don't need to change any packages 🤞 

✅ I granted you access to @lewagon-assess

**Comment by ajdubovoy** [comment]
Sounds good. Hm, yeah I doubt the JS update will break anything tbh since the students _barely_ use `node` anymore. I'd be more concerned about the Ruby one, but it's fortunately a smaller update.

Thank you! I just looked through though and I actually didn't see any repos tagged `web` in that org haha?

**Comment by ajdubovoy** [comment]
@nguiban just looping you in here as well 🚀

**Comment by nguiban** [comment]
Hello ! 
I was looking at the roadmap for web dev. In March, we're going to struggle a bit to plan that, but would it be a good idea to schedule it for May-June before the July batches?

**Comment by ajdubovoy** [comment]
Also works for me! Nothing is breaking because of this, it's just maintenance we need to eventually do

**Comment by wJoenn** [comment]
@ajdubovoy @Eschults Just in case you guys don't know about that but Webpack is not compatible with Node 17+ because Node has migrated to OpenSSL3 and Webpack 4 still relies on legacy ssl protocols.

It's still possible to use a webpack 4 command by exporting the `NODE_OPTIONS=--openssl-legacy-provider` ENV var before running the command but at this point you guys should really considerate moving on from Webpack 4 which has been EOLed for a few years already.

Back in my by batch we had a couple slides about how Webpack is the industry standard and that's why LeWagon is still sticking to it (if that's still what you want then bump to v5) but as far as frontend development goes Vite has really become the golden standard in any project that can use it and it's also easier to setup for you and easier to understand for the students so imo you should drop Webpack completely (which you have already done for Rails after switching to importmaps) and go with Vite instead

**Comment by ajdubovoy** [comment]
Hi @wJoenn as far as I'm aware we've fully dropped Webpack from the curriculum already and use no-build setups in the entire front end unit and in Rails 😊

**Comment by wJoenn** [comment]
It's still inside the frontend unit's package.json
https://github.com/lewagon/fullstack-challenges/blob/master/04-Front-End/package.json

**Comment by ajdubovoy** [comment]
We could probably remove it because it's never used in a challenge
