### ISSUE TITLE
Check the locale position

### ISSUE THREAD

**Issue by v-natalia** [lewagon/setup#462]
Hey!

[Check the locale](https://github.com/lewagon/setup/blob/master/windows.md#check-the-locale)
This step in setup is way to ahead, the students  are getting errors because apt is not updated yet, I suggest moving it to 
after [ZSH installation](https://github.com/lewagon/setup/blob/master/windows.md#oh-my-zsh)

Also, the section:

> Generate locale
> Please, run this lines in your terminal.
> 
> sudo update-locale LANG=en_US.UTF8
> sudo apt-get install language-pack-en language-pack-en-base manpages
> exec zsh
> You can now close this terminal window.

Should be added to the data-setup, and moved to the same part :pray:

**Comment by julesvanrie** [comment]
I have just run this myself as I was doing the data-setup on my brand new computer and wanted to check if our setup still functions properly.

This part of web setup will be integrated when I update the data-setup. (PR pending for something else will do this.)

But there are indeed a couple of problems if one needs to go through the "Generate locale" part.
@ajdubovoy I think we can do a quick fix to solve (easier than moving it around):
- Add a line to `sudo apt-get update` otherwise `apt-get install` fails indeed.
- The `exec zsh` will fail because zsh is not yet installed. Just drop the line. It's not needed because we close the terminal window anyway in the next step.
