### ISSUE TITLE
WARNING: npm install --global yarn 

### ISSUE THREAD

**Issue by GianClaudioScarafini** [lewagon/setup#464]
ISSUE
within the readme file, you have instructed to use :

`npm install --global yarn`

this returns a WARN :
`npm WARN config global `--global`, `--local` are deprecated.`

**Comment by GianClaudioScarafini** [comment]
SOLUTION
this might be the  solution:
npm install yarn --location=global

**Comment by ajdubovoy** [comment]
Hm (looping in @Eschults here). I checked the yarn docs and they actually fully recommend against installing globally now.

https://yarnpkg.com/corepack

Instead, it now comes as part of Corepack. So, they say to run:

```bash
corepack enable
```

With all `node` versions >14, this should come by default. But if you get any errors, you can run `npm install -g corepack` to install it.

So, do we feel OK if I update setup to recommend this? I'm a bit scared to do so, since it's hard for me to test, since I don't have a blank system to try running it on from scratch. I guess if we want I could spin out a Digital Ocean droplet and try running our Ubuntu setup on it with this command and see if it works?

**Comment by Eschults** [comment]
👋 @ajdubovoy, OK to update the setup w/ the latest Yarn recommendations, for this kind of short tests on different systems I would suggest involving senior teachers of our community and kindly ask them if they can run the commands, Engineering has very low bandwidth and cannot provide you w/ this kind of support at the minute 🙏

**Comment by ajdubovoy** [comment]
Ok sounds good!

**Comment by Eschults** [comment]
🟢
