### ISSUE TITLE
Hub browse doesn't work

### ISSUE THREAD

**Issue by barangerbenjamin** [lewagon/setup#66]
Hello,

In WSL, `hub browse` will render the error `Please set $BROWSER to a web launcher to use this command`

Fix: 

*For Google chrome browser*
```echo "export BROWSER=/mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe" >> ~/.zshrc```
Restart your terminal
`hub browse` should now open chrome

*For Firefox browser*
```echo "export BROWSER=/mnt/c/Program\ Files\ \(x86\)/Mozilla\ Firefox/firefox.exe" >> ~/.zshrc```
Restart your terminal
`hub browse` should now open firefox

**Comment by barangerbenjamin** [comment]
@ssaunier @krokrob Does this belong in the setup ? Or should it be part of a wiki ?

**Comment by ssaunier** [comment]
You can make it part of the setup

**Comment by nikotikcho** [comment]
Merci beaucoup!

**Comment by barangerbenjamin** [comment]
Closing this issue has it's been implemented in the setup
https://github.com/lewagon/setup/blob/master/WINDOWS_LINUX_SUBSYSTEM.md

**Comment by imba-tjd** [comment]
I don't know whether it's because I'm using bash. That command didn't work for me. My browser is `"C:\Program Files\Mozilla Firefox\firefox.exe"`. I tried:

```
export BROWSER=/mnt/c/Program\ Files\Mozilla\ Firefox/firefox.exe
export BROWSER="/mnt/c/Program Files\Mozilla Firefox/firefox.exe"
export BROWSER="'/mnt/c/Program\ Files\Mozilla\ Firefox/firefox.exe'"
```

The first two I got: `exec: "/mnt/c/Program": command not found`, and the third is `Unterminated single-quoted string`.

In the end I added firefox to path and set `export BROWSER=firefox.exe`, which solved my problem.
